#!/bin/bash

function bwl() {
    local password="$1"
    local code="$2"
    export BW_SESSION=$(bw login andrewgonzo23@gmail.com "$password" --method 0 --code "$code" --raw)
}

function bwls() {
    bw list items | jq '.[].name'
}

function bwg() {
    bw get item "$1" | jq '.login'
}

function g(){

    if [[ "$1" == 'work' ]]; then
        GIT_TOKEN=$(bw get item GIT_TOKEN_WORK | jq '.login.password')
    else
        GIT_TOKEN=$(bw get item GIT_TOKEN | jq '.login.password')
    fi
    
    if [ -z "${GIT_TOKEN}" ]; then
        export "${GIT_TOKEN}"
        green "Setting env var: GIT_TOKEN."
    else
        red "Error setting env var: GIT_TOKEN."
    fi

}