#!/bin/bash

function red {
    echo -e "\e[38;2;255;10;30m"
    echo -e "$1"
    echo -e "\e[0m"
}

function green {
    echo -e "\e[38;2;0;255;0m"
    echo -e "$1"
    echo -e "\e[0m"
}

function yellow {
    echo -e "\e[38;2;255;255;0m"
    echo -e "$1"
    echo -e "\e[0m"
}

function gold {
    echo -e "\e[38;2;184;138;0m"
    echo -e "$1"
    echo -e "\e[0m"
}

function cyan {
    echo -e "\e[38;2;0;255;255m"
    echo -e "$1"
    echo -e "\e[0m"
}